# Generated by Django 6.0.6 on 2026-07-03 06:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('category', models.CharField(choices=[('positive', 'Позитивный сигнал'), ('risk', 'Риск'), ('low_quality', 'Низкое качество'), ('system', 'Системный')], default='positive', max_length=32, verbose_name='категория')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'флаг лида',
                'verbose_name_plural': 'флаги лидов',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MailboxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('gmail_search_query', models.CharField(blank=True, default='from:(kleinanzeigen.de)', max_length=500, verbose_name='Gmail search query')),
                ('connection_status', models.CharField(choices=[('not_connected', 'Не подключен'), ('connected', 'Подключен'), ('error', 'Ошибка'), ('disabled', 'Отключен')], default='not_connected', max_length=32, verbose_name='статус подключения')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя проверка')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='последний успех')),
                ('last_error', models.TextField(blank=True, verbose_name='последняя ошибка')),
            ],
            options={
                'verbose_name': 'почтовый ящик',
                'verbose_name_plural': 'почтовые ящики',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('event_type', models.CharField(choices=[('buyer_message', 'Сообщение покупателя'), ('listing_expiring', 'Объявление истекает'), ('system_notice', 'Системное уведомление'), ('noise', 'Шум')], default='buyer_message', max_length=32, verbose_name='тип события')),
                ('alert_status', models.CharField(choices=[('unread', 'Новое'), ('in_work', 'В работе'), ('ignored', 'Игнор')], default='unread', max_length=32, verbose_name='статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=32, verbose_name='приоритет')),
                ('parse_status', models.CharField(choices=[('success', 'Успешно'), ('partial', 'Частично'), ('error', 'Ошибка'), ('skipped', 'Пропущено')], default='success', max_length=32, verbose_name='статус парсинга')),
                ('parse_error', models.TextField(blank=True, verbose_name='ошибка парсинга')),
                ('listing_id', models.CharField(blank=True, max_length=120, verbose_name='ID объявления')),
                ('listing_title', models.CharField(blank=True, max_length=255, verbose_name='название объявления')),
                ('buyer_name', models.CharField(blank=True, max_length=150, verbose_name='покупатель')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='тема')),
                ('message_text', models.TextField(blank=True, verbose_name='сообщение')),
                ('raw_subject', models.CharField(blank=True, max_length=500, verbose_name='исходная тема')),
                ('raw_body', models.TextField(blank=True, verbose_name='исходное тело письма')),
                ('normalized_body', models.TextField(blank=True, verbose_name='нормализованное тело письма')),
                ('gmail_message_id', models.CharField(blank=True, max_length=255, verbose_name='Gmail message ID')),
                ('gmail_thread_id', models.CharField(blank=True, max_length=255, verbose_name='Gmail thread ID')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='получено')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='обработано')),
                ('flags', models.ManyToManyField(blank=True, related_name='alerts', to='alerts.leadflag', verbose_name='флаги')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.mailboxaccount', verbose_name='почтовый ящик')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'ordering': ['-received_at', '-created_at'],
                'indexes': [models.Index(fields=['alert_status', 'priority'], name='alerts_mark_alert_s_cce3f3_idx'), models.Index(fields=['event_type'], name='alerts_mark_event_t_9b00d1_idx'), models.Index(fields=['listing_id'], name='alerts_mark_listing_463494_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('gmail_message_id', models.CharField(max_length=255, verbose_name='Gmail message ID')),
                ('gmail_thread_id', models.CharField(blank=True, max_length=255, verbose_name='Gmail thread ID')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='тема')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='получено')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='обработано')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to='alerts.mailboxaccount', verbose_name='почтовый ящик')),
            ],
            options={
                'verbose_name': 'обработанное письмо',
                'verbose_name_plural': 'обработанные письма',
                'ordering': ['-processed_at'],
                'constraints': [models.UniqueConstraint(fields=('mailbox', 'gmail_message_id'), name='unique_processed_email_per_mailbox')],
            },
        ),
    ]
