# Generated by Django 6.0.6 on 2026-07-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadflag',
            options={'ordering': ['category', 'name'], 'verbose_name': 'флаг обращения', 'verbose_name_plural': 'флаги обращений'},
        ),
        migrations.AlterModelOptions(
            name='marketplacealert',
            options={'ordering': ['-received_at', '-created_at'], 'verbose_name': 'обращение', 'verbose_name_plural': 'обращения'},
        ),
    ]
