# Generated by Django 6.0.6 on 2026-07-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_leadflag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacealert',
            name='classification_reason',
            field=models.TextField(blank=True, verbose_name='объяснение классификации'),
        ),
    ]
