# Generated by Django 6.0.6 on 2026-07-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_marketplacealert_classification_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacealert',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram chat ID'),
        ),
        migrations.AddField(
            model_name='marketplacealert',
            name='telegram_error',
            field=models.TextField(blank=True, verbose_name='ошибка Telegram'),
        ),
        migrations.AddField(
            model_name='marketplacealert',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram message ID'),
        ),
        migrations.AddField(
            model_name='marketplacealert',
            name='telegram_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='отправлено в Telegram'),
        ),
    ]
