# Generated by Django 6.0.6 on 2026-07-05 17:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_mailboxaccount_gmail_oauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('event_type', models.CharField(choices=[('mailbox_error', 'Ошибка mailbox'), ('parser_error', 'Ошибка parser'), ('telegram_send_error', 'Ошибка Telegram send'), ('recovery', 'Восстановление')], max_length=32, verbose_name='тип события')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=16, verbose_name='важность')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('recovered', 'Восстановлено')], default='open', max_length=16, verbose_name='статус')),
                ('source', models.CharField(blank=True, max_length=80, verbose_name='источник')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('details', models.TextField(blank=True, verbose_name='детали')),
                ('fingerprint', models.CharField(db_index=True, max_length=255, verbose_name='fingerprint')),
                ('occurrences', models.PositiveIntegerField(default=1, verbose_name='повторы')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='первое событие')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='последнее событие')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='восстановлено')),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено в Telegram')),
                ('telegram_error', models.TextField(blank=True, verbose_name='ошибка Telegram')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_events', to='alerts.marketplacealert', verbose_name='обращение')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_events', to='alerts.mailboxaccount', verbose_name='почтовый ящик')),
            ],
            options={
                'verbose_name': 'service event',
                'verbose_name_plural': 'service events',
                'ordering': ['-last_seen_at', '-created_at'],
                'indexes': [models.Index(fields=['event_type', 'status'], name='alerts_serv_event_t_adea16_idx'), models.Index(fields=['severity', 'status'], name='alerts_serv_severit_dedcb7_idx'), models.Index(fields=['fingerprint', 'status'], name='alerts_serv_fingerp_a9c30c_idx')],
            },
        ),
    ]
