# Generated by Django 6.0.6 on 2026-07-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_serviceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacealert',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последний reminder'),
        ),
    ]
