# Generated by Django 6.0.6 on 2026-07-06 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_marketplacealert_last_reminded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='quiet hours включены')),
                ('quiet_hours_start', models.TimeField(default=datetime.time(22, 0), verbose_name='quiet hours начало')),
                ('quiet_hours_end', models.TimeField(default=datetime.time(7, 0), verbose_name='quiet hours конец')),
                ('allow_urgent_during_quiet_hours', models.BooleanField(default=False, verbose_name='отправлять срочные alerts в quiet hours')),
            ],
            options={
                'verbose_name': 'настройки Telegram',
                'verbose_name_plural': 'настройки Telegram',
            },
        ),
    ]
