# Generated by Django 6.0.6 on 2026-07-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_telegramsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseAlert',
            fields=[
            ],
            options={
                'verbose_name': 'noise / spam',
                'verbose_name_plural': 'noise / spam',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('alerts.marketplacealert',),
        ),
    ]
