# Generated by Django 6.0.6 on 2026-07-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_noisealert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadflag',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Приоритет обращения', 'verbose_name_plural': 'Приоритеты обращений'},
        ),
        migrations.AlterModelOptions(
            name='mailboxaccount',
            options={'ordering': ['email'], 'verbose_name': 'Почтовый ящик', 'verbose_name_plural': 'Почтовые ящики'},
        ),
        migrations.AlterModelOptions(
            name='marketplacealert',
            options={'ordering': ['-received_at', '-created_at'], 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='noisealert',
            options={'verbose_name': 'Письмо из спама или рассылки', 'verbose_name_plural': 'Спам и рассылки'},
        ),
        migrations.AlterModelOptions(
            name='processedemail',
            options={'ordering': ['-processed_at'], 'verbose_name': 'Проверенное письмо', 'verbose_name_plural': 'Проверенные письма'},
        ),
        migrations.AlterModelOptions(
            name='serviceevent',
            options={'ordering': ['-last_seen_at', '-created_at'], 'verbose_name': 'Запись журнала системы', 'verbose_name_plural': 'Журнал системы'},
        ),
        migrations.AlterModelOptions(
            name='telegramsettings',
            options={'verbose_name': 'Настройки Telegram', 'verbose_name_plural': 'Настройки Telegram'},
        ),
    ]
