# Generated by Django 6.0.6 on 2026-07-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alter_leadflag_options_alter_mailboxaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacealert',
            name='alert_status',
            field=models.CharField(choices=[('unread', 'Новое'), ('in_work', 'В работе'), ('ignored', 'Игнор'), ('archived', 'Архив')], default='unread', max_length=32, verbose_name='статус'),
        ),
    ]
