# Generated by Django 6.0.6 on 2026-07-06 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alter_leadflag_options_alter_mailboxaccount_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacealert',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='взято в работу'),
        ),
        migrations.AddField(
            model_name='marketplacealert',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_alerts_in_work', to=settings.AUTH_USER_MODEL, verbose_name='кто взял в работу'),
        ),
        migrations.AddField(
            model_name='marketplacealert',
            name='taken_by_label',
            field=models.CharField(blank=True, max_length=160, verbose_name='исполнитель'),
        ),
    ]
