# Generated by Django 6.0.6 on 2026-07-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alter_marketplacealert_alert_status'),
        ('alerts', '0014_serviceevent_ignored_status'),
    ]

    operations = []
