# Generated by Django 6.0.6 on 2026-07-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0015_merge_archive_status_and_serviceevent_ignored'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ru', 'Russian')], default='en', help_text='Global language for Admin, mobile panel, and operational UI.', max_length=8, verbose_name='Interface language')),
            ],
            options={
                'verbose_name': 'Argus settings',
                'verbose_name_plural': 'Argus settings',
            },
        ),
    ]
