# Generated by Django 6.0.6 on 2026-07-10 06:34

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0016_argus_settings_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadflag',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Lead priority rule', 'verbose_name_plural': 'Lead priority rules'},
        ),
        migrations.AlterModelOptions(
            name='mailboxaccount',
            options={'ordering': ['email'], 'verbose_name': 'Mailbox', 'verbose_name_plural': 'Mailboxes'},
        ),
        migrations.AlterModelOptions(
            name='marketplacealert',
            options={'ordering': ['-received_at', '-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='noisealert',
            options={'verbose_name': 'Spam or newsletter email', 'verbose_name_plural': 'Spam and newsletters'},
        ),
        migrations.AlterModelOptions(
            name='processedemail',
            options={'ordering': ['-processed_at'], 'verbose_name': 'Processed email', 'verbose_name_plural': 'Processed emails'},
        ),
        migrations.AlterModelOptions(
            name='serviceevent',
            options={'ordering': ['-last_seen_at', '-created_at'], 'verbose_name': 'System log entry', 'verbose_name_plural': 'System log'},
        ),
        migrations.AlterModelOptions(
            name='telegramsettings',
            options={'verbose_name': 'Telegram settings', 'verbose_name_plural': 'Telegram settings'},
        ),
        migrations.AlterField(
            model_name='argussettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='argussettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='leadflag',
            name='category',
            field=models.CharField(choices=[('positive', 'Positive signal'), ('risk', 'Risk'), ('low_quality', 'Low quality'), ('system', 'System')], default='positive', max_length=32, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='leadflag',
            name='code',
            field=models.SlugField(max_length=80, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='leadflag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='leadflag',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='leadflag',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='leadflag',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='leadflag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='connection_status',
            field=models.CharField(choices=[('not_connected', 'Not connected'), ('connected', 'Connected'), ('error', 'Error'), ('disabled', 'Disabled')], default='not_connected', max_length=32, verbose_name='connection status'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='gmail_connected_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='connected Gmail'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='gmail_oauth_connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gmail connected at'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='gmail_oauth_error',
            field=models.TextField(blank=True, verbose_name='Gmail OAuth error'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='gmail_oauth_last_refresh_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last Gmail token refresh'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last check'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='last error'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last success'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mailboxaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='alert_status',
            field=models.CharField(choices=[('unread', 'New'), ('in_work', 'In work'), ('ignored', 'Ignored'), ('archived', 'Archived')], default='unread', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='buyer'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='classification_reason',
            field=models.TextField(blank=True, verbose_name='classification explanation'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='event_type',
            field=models.CharField(choices=[('buyer_message', 'Buyer message'), ('listing_expiring', 'Listing expiring'), ('system_notice', 'System notice'), ('noise', 'Noise')], default='buyer_message', max_length=32, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='flags',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='alerts.leadflag', verbose_name='flags'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last reminder'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='listing_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='listing ID'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='listing_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='listing title'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.mailboxaccount', verbose_name='mailbox'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='message_text',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='normalized_body',
            field=models.TextField(blank=True, verbose_name='normalized email body'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='parse_error',
            field=models.TextField(blank=True, verbose_name='parse error'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='parse_status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('error', 'Error'), ('skipped', 'Skipped')], default='success', max_length=32, verbose_name='parse status'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=32, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='processed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='processed at'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='raw_body',
            field=models.TextField(blank=True, verbose_name='raw email body'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='raw_subject',
            field=models.CharField(blank=True, max_length=500, verbose_name='raw subject'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='received at'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='subject',
            field=models.CharField(blank=True, max_length=500, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='taken at'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_alerts_in_work', to=settings.AUTH_USER_MODEL, verbose_name='taken by'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='taken_by_label',
            field=models.CharField(blank=True, max_length=160, verbose_name='owner label'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='telegram_error',
            field=models.TextField(blank=True, verbose_name='Telegram error'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='telegram_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sent to Telegram at'),
        ),
        migrations.AlterField(
            model_name='marketplacealert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to='alerts.mailboxaccount', verbose_name='mailbox'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='processed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='processed at'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='received at'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='subject',
            field=models.CharField(blank=True, max_length=500, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='processedemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_events', to='alerts.marketplacealert', verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='details',
            field=models.TextField(blank=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='event_type',
            field=models.CharField(choices=[('mailbox_error', 'Mailbox error'), ('parser_error', 'Parser error'), ('telegram_send_error', 'Telegram send error'), ('recovery', 'Recovery')], max_length=32, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='first_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='first seen at'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last seen at'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='mailbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_events', to='alerts.mailboxaccount', verbose_name='mailbox'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='occurrences',
            field=models.PositiveIntegerField(default=1, verbose_name='occurrences'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='resolved at'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=16, verbose_name='severity'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='source',
            field=models.CharField(blank=True, max_length=80, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('recovered', 'Recovered'), ('ignored', 'Ignored')], default='open', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='telegram_error',
            field=models.TextField(blank=True, verbose_name='Telegram error'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='telegram_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sent to Telegram at'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='allow_urgent_during_quiet_hours',
            field=models.BooleanField(default=False, verbose_name='send urgent alerts during quiet hours'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False, verbose_name='quiet hours enabled'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='quiet_hours_end',
            field=models.TimeField(default=datetime.time(7, 0), verbose_name='quiet hours end'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='quiet_hours_start',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='quiet hours start'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
